Forms/urls.py
from django.urls import path
from .views import (detailsick,
 home, get_name,
Submit_Form
 , payment,check_transaction,
 detailform, Unsubmit_Payment
)
app_name = "form"

urlpatterns = [
    path("home", home.as_view(), name="home"),
    path("submit", Submit_Form.as_view(), name="submit"),
    path("Unsubmit", Unsubmit_Payment.as_view(), name="Unsubmit"),
    path("fomes", get_name, name="formviews"),
    path("<slug:slug>/", detailsick, name="h"),
    #path("<int:pk>/<slug:slug>", detailview.as_view(), name="details"),
    path("c/<int:pk>/<slug:slug>/<int:id>", detailform, name="detailss"),
    path("payment/<slug:slug>/<int:id>", payment, name="payment"),
    path("checkss/<slug:slug>/<int:id>/", check_transaction,name="checks"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Forms.urls')),
    path('', include('sms.urls')),
    path('', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path
from .views import send_sms
app_name = "sms-app"

urlpatterns = [
    #path("<slug:slug>/", detailsick, name="h"),
    path("send-sms", send_sms, name="send_sms")
]

Forms/models.py
from django.db import models

class darmangar(models.Model):
    choics = [
        ("طلاق","طلاق"),
        ("فرزند","فرزند"),
        ("خانواده","خانواده"),
    ]
    keyword = models.CharField(max_length=20, choices=choics, default=1)
    fname = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, null=True, unique=True )
    lname = models.CharField(max_length=100)
    description = models.TextField()
    pic = models.ImageField(upload_to="darmanger-image")
    price = models.IntegerField(default=0)


    def __str__(self):
        return self.fname + " " + self.lname 

class info(models.Model):
    fname = models.CharField(max_length=100, blank=False)
    lname = models.CharField(max_length=100, blank=False)
    mobile = models.IntegerField()
    email = models.EmailField(blank=False)
    slug = models.CharField(max_length=20, unique=True, null=True)
    
    def __str__(self):
        return str(self.id)

class UploadFile(models.Model):
    upl = models.FileField(upload_to="upload-file")



class darmanjo_form(models.Model):
    talk_about = models.TextField(null=True, blank=True)
    information = models.ForeignKey(info, on_delete=models.CASCADE,null=True)
    rel_info = models.ForeignKey(darmangar, on_delete=models.CASCADE,null=True, blank=True)
    payment = models.BooleanField(default=False)
    #picture = models.forignkey(darmangar, models/CASCADE)


class Choice_Model(models.Model):
    choics = [
        ("طلاق","طلاق"),
        ("فرزند","فرزند"),
        ("خانواده","خانواده"),
    ]
    keyword = models.CharField(max_length=20, choices=choics, default=1)
    information = models.ForeignKey(info, on_delete=models.CASCADE,null=True)
    sessions = models.CharField(max_length=200)

Forms/forms.py
from django import forms
from django.db import models

from django.forms import ModelForm
from .models import UploadFile, info, darmanjo_form, darmangar, Choice_Model

class infoss(ModelForm):
    class Meta:
        model = UploadFile
        fields = "__all__"

class darmanjo_formss(ModelForm):
    class Meta:
        model = darmanjo_form
        fields = ['talk_about','rel_info']


    #rel_info = forms.ModelMultipleChoiceField(
        #queryset=darmangar.objects.all(), widget=forms.CheckboxSelectMultiple)

Forms/views.py
from audioop import reverse
import json
import math
from wsgiref import headers
from xml.dom import ValidationErr
from numpy import append
from .models import Choice_Model, darmangar, info, darmanjo_form
from django.core.paginator import Paginator
from django.urls import reverse
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView,FormView, DetailView
from .forms import infoss, darmanjo_formss
from .extentions.excel_validation import exel_reader
import xlrd
from django.utils.crypto import get_random_string
import random
from pypep import Pasargad, ApiError
import pandas as pd
import datetime

class home(TemplateView):
    template_name = "forms/home.html"



#in yek method form baraye in ast ke file excel ra daryaft konad
def get_name(request):
    if request.method == 'POST':
        form = infoss(request.POST, request.FILES)
        if form.is_valid():
            upl = form.cleaned_data['upl']
            form.save()

            wb = xlrd.open_workbook("media/upload-file/" + str(upl))
            sh = wb.sheet_by_index(0)
            columns = sh.ncols - 2
            num_rows = sh.nrows - 1
            print(num_rows)
            if sh.cell_value(0,0) == "نام" and sh.cell_value(0,1) == "خانوادگی" and sh.cell_value(0,2) == "موبایل" and sh.cell_value(0,3) == "ایمیل":
                for i in range(num_rows):
                    the_slug = get_random_string(3,'0123456789') # 8 characters, only digits. 
                    the_slugs = get_random_string(3,'0123456789')
                    m = str(the_slug) + "-" + str(the_slug)
                    o = i + 1

                    d =  sh.cell_value(o,2)

                    a = info.objects.create( mobile=d)
                return HttpResponse("فایل با موفقیت ثبت شد")
            else:
                return HttpResponse("مشکلی در فایل وجود دارد احتمالا از قوانین فایل پیروی نکردید")
            #return HttpResponseRedirect('home')
    else:
        form = infoss()

    return render(request, 'forms/form.html', {'form': form})



class Submit_Form(TemplateView):
    template_name = "forms/submit.html"




#function form baraye form darmanjo
def detailsick(request, slug):
    deta = get_object_or_404(info, slug=slug)
    detas = info.objects.get(slug=slug)
    darm = None
    informations = None
    page_obj = None
    darms = []
    rel_info = None
    list_count =[]
    #form
    if request.method == "POST":
        form = darmanjo_formss(request.POST)
        a = request.POST
        if form.is_valid():
            global talk_about
            talk_about = form.cleaned_data['talk_about']
            form.save(commit=False)
            print("aa"+str(rel_info))
            darm = darmangar.objects.filter(keyword__in=talk_about.split())
            count = darm.count()
            half_count = math.ceil(count/2)
            print(half_count)

            for x in range(half_count):
                list_count.append(x+1)

            print(list_count)
            print(darms)
            informations = darmanjo_form.objects.create(information=deta, talk_about=talk_about)
    else:
        form = darmanjo_formss()
    return render(request, "forms/detailsick.html", {'deta':deta,'detas':detas,'form':form,'darm':darm,'page_obj':page_obj,'darms':darms, 'list_count':list_count, 'informations':informations})

#detail form
def detailform(request, slug, pk, id):
    #for url filter
    darmanjo_fo = darmanjo_form.objects.get(id=id)
    fname = None
    lname = None
    deta = info.objects.filter(slug=slug)
    deta1 = info.objects.get(slug=slug)
    darman = get_object_or_404(darmangar, pk=pk)
    detass = info.objects.get(slug=slug)
    c = info.objects.get(slug=slug)
    #informations = darmanjo_form.objects.update(talk_about=detas,rel_info=darman, information = detas)
    informations = darmanjo_form.objects.filter(information__fname__icontains=deta1.fname, information__lname__icontains=deta1.lname,id=darmanjo_fo.id).update(rel_info=darman, information=detass)
 
    return render(request, 'forms/detailform.html', {'deta':deta,'darman':darman,'detass':detass,'darmanjo_fo':darmanjo_fo})


class Unsubmit_Payment(TemplateView):
    template_name = "forms/Unsubmit.html"

#payment
def payment(request, slug,id):

    darmanjo_fo = darmanjo_form.objects.get(id=id)
    date = datetime.datetime.now()
    global invoice_number
    payment_price = darmangar.objects.get(slug=slug)
    global amount
    amount = int(payment_price.price)
    print(payment_price)
    url = f'http://127.0.0.1:8000/checkss/{payment_price.slug}/{darmanjo_fo.id}/'
    pasargad = Pasargad(4916435, 2148370, url, 'cert.xml')
    payment_url = pasargad.redirect(
        amount=amount,
        invoice_number=random.randint(0, 9000000),
        invoice_date=str(date),
    )
    url = 'http://127.0.0.1:8000/checkss/{payment_price.slug}/{darmanjo_fo.id}/'
    return HttpResponseRedirect(payment_url, url)

def check_transaction(request,slug,id):
    payment_price = darmangar.objects.get(slug=slug)
    darmanjo_fo = darmanjo_form.objects.get(id=id)
    global amount
    amount = int(payment_price.price)
    print(payment_price)
    pasargad = Pasargad(4916435, 2148370, 'http://127.0.0.1:8000/home', 'cert.xml')
    print("okey")
    TransactionReferenceID = request.GET.get('tref')
    InvoiceNumber = request.GET.get('iN')
    InvoiceDate = request.GET.get('iD')
    print(TransactionReferenceID)
    print(InvoiceNumber)
    print(InvoiceDate)
    try:
        response = pasargad.check_transaction(
            reference_id=TransactionReferenceID,
            invoice_number=InvoiceNumber,
            invoice_date=InvoiceDate,
        )
        
        with open('data.txt', 'a') as f:
            data = json.dumps(response)
            data1 = str(data)
            f.write(data1+"\n")
            print("okey")
        InvoiceNumber = request.GET.get('iN')
        InvoiceDate = request.GET.get('iD')
        response = pasargad.verify_payment(
            amount=amount,
            invoice_number=InvoiceNumber,
            invoice_date=InvoiceDate,
        )
        informations = darmanjo_form.objects.filter(id=darmanjo_fo.id).update(payment=True)
        print("sabt shod")
    #informations = darmanjo_form.objects.create()
        return HttpResponseRedirect(reverse('form:home'))
    except Exception:
        return HttpResponseRedirect(reverse('form:Unsubmit'))


        #response = json.loads(response.read().decode('utf-8'))


#f'http://127.0.0.1:8000/checkss/{payment_price.slug}/{darmanjo_fo.id}/'
#f'http://127.0.0.1:8000/checkss/{payment_price.slug}/{deta.pk}/{deta.fname}/{darmanjo_fo.id}/'


"""
        if request.method == 'GET':
            informations = darmanjo_form.objects.filter(id=darmanjo_fo.id).update(payment=True)
            InvoiceNumber = request.GET.get('iN')
            InvoiceDate = request.GET.get('iD')
            response = pasargad.verify_payment(
                amount=amount,
                invoice_number=InvoiceNumber,
                invoice_date=InvoiceDate,
            )
            #informations = darmanjo_form.objects.create()
            return HttpResponse("okey")
    except Exception:
        return HttpResponse("okey")
"""
"""
    pasargad = Pasargad(4916435, 2148370, f'http://127.0.0.1:8000/home', 'cert.xml')
    response = pasargad.check_transaction(
        reference_id=request.GET['tref'],
        invoice_number=request.GET['iN'],
        invoice_date=request.GET['iD'],
    )
    with open('data.txt', 'a') as f:
        data = json.dumps(response)
        data1 = str(data)
        f.write(data1+"\n")
    
    data = json.dumps(response)
    print(data)
    x = data.get("IsSuccess")
    print("<-------------------------->  "+x)
    if x == "True":
        if request.method == 'GET':
            informations = darmanjo_form.objects.filter(information__fname__icontains=deta1.fname, information__lname__icontains=deta1.lname,id=darmanjo_fo.id).update(payment=True)
            InvoiceNumber = request.GET.get('iN')
            InvoiceDate = request.GET.get('iD')
            response = pasargad.verify_payment(
                amount="17000",
                invoice_number=InvoiceNumber,
                invoice_date=InvoiceDate,
            )
            #informations = darmanjo_form.objects.create()
            return HttpResponse("okey")
    else:
        return HttpResponse("False")

"""

templates/forms/a.html
<form method="post">
    {% csrf_token %}
    {{form.talk_about}}
    <button type="submit">Save</button>
</form>

templates/forms/choice.html
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>

templates/forms/detail.html
<center><h1>{{object.fname}} {{object.lname}} خوش آمدید</h1>

    <!DOCTYPE html>
    <html>
    <head>
        <title>Todo List</title>
    </head>
    <body>
        <form method="post" id="task-form">
            {% csrf_token %}
            {{form.talk_about}}
            <button class="button" type="submit">جست و جو دکتر</button>
            {% for i in darm %}
            <p>{{i.fname}} {{i.lname}}</p>
            <p>{{i.description}}</p>
             <img src="{{i.pic.url}}" alt="" width="400" height="400">
             <button class="button" type="submit">جست و جو دکتر</button>
            {% endfor %}
        </form>
    </body>
    </html>
  </center>
  </body>

templates/forms/detailform.html
{% extends 'base.html' %}
{% block content %}
<center>
  <div class="bg-white">
  <div class="col-6">
    <img src="{{darman.pic.url}}" class="mt-3" alt="aa" style="width=500px; height:600px" >

<h1 class="text-dark mt-3"> دکتر {{darman.fname}} 
{{darman.lname}}</h1> <br>
<p>قیمت:{{darman.price}}</p><br><br>
<p class="text-dark text-muted font-5">:توضیحات دکتر {{darman.description}}</p><br><br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <a href="{% url 'form:payment' darman.slug darmanjo_fo.id %}"target="_blank">aaa
    </a>
    <input type="submit" class="btn btn-primary btn-lg active mb-3" role="button" aria-pressed="true" value="ثبت فرم">
</form>
</div>
</div>
</center>
{% endblock %}

templates/forms/detailsick.html
{% extends 'base.html' %}
{% block content %}
<style>
    input[type=text], select {
      width: 100%;
      height:200px;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }
    
    input[type=submit] {
      width: 100%;
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    
    input[type=submit]:hover {
      background-color: #45a049;
    }
    
    #div {
      border-radius: 11px;
      background-color: #f2f2f2;
      padding: 20px;
    }
    </style>

        <!--.survey-desc-->
        <form method="POST">
            {% csrf_token %}
            <br>
            <div class="col-md-6 mx-auto" id="div">
            <label for="fname">مشکلت چیه؟</label>
            <input type="text" id="talk_about" name="talk_about" placeholder="مشکلت چیه؟">
                <button type="submit"class="btn btn-primary btn-lg active" role="button" aria-pressed="true">ثبت</button>
            </form>
            </div>

        </form>
        <div class="bg-white p-3">
            <section class="mb-4">
                <div class="container">
                    <br><br><h4 class="text-left text-white">دکتر های جست و جو شده</h4><hr>
                <div class="row">
                    {% for i in darm %}
                        {% comment %} {% for j in i %} {% endcomment %}
                            <div class="col-6 darm" id="darm{{forloop.counter0}}" > 
                                <div class="card mb-3" style="box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px; width: auto; height: auto; border-radius: 10px;">
                            <div class="card-body">
                                <img src="{{i.pic.url}}" class="card-img-top" alt="aa" style="width=auto; height:auto" >
                                <h5 class="card-title mb-3">{{i.fname}} {{i.lname}}</h5>
                                <p class="card-title mb-3 ">{{i.description|truncatewords:30}}</p>

                                <a href="{% url 'form:detailss' i.pk detas.slug informations.id %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">ادامه</a>
                            </div>
                            </div>
                            </div>

                        {% comment %} {% endfor %}         {% endcomment %}
                {% endfor %} 
                <div class="row">
                   {%for x in list_count%}
                   <div class="col-sm-1">
                       <button class="btn btn-success" name="pagination{{x}}" id="pagination{{x}}" onclick="next({{x}})">{{x}}</button>
                   </div>
                       {%endfor%}
               </div>

             </div>
              
            </section>
            <script>
            
                function none(){
                $('.darm').css('display','none');
                } 
                none();   
                 var i = 0;
                for(i;i<=1;i++)
                {
                   $('#darm'+i).css('display','block');
                    
                }
                function next(x)
                {
                    x=x-1;
                    x=x*2;
                    none();
                    $('#darm'+x).css('display','block');
                    $('#darm'+(x+1)).css('display','block');
                }
                function nexts(y){
                    y++
                }
 
            </script>

{% endblock %}

templates/forms/detailview.html
{% extends 'base.html' %}
{% block content %}
<center>
  <div class="bg-white">
  <div class="col-6">
    <img src="{{details.pic.url}}" class="mt-3" alt="aa" style="width=500px; height:600px" >

<h1 class="text-dark mt-3"> دکتر {{details.fname}} 
{{details.lname}}</h1> <br>
<p>قیمت:{{details.price}}</p><br><br>
<p class="text-dark text-muted font-5">:توضیحات دکتر {{details.description}}</p><br><br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <a href="{% url 'form:payment' details.slug details.pk %}"><input type="submit" class="btn btn-primary btn-lg active mb-3" role="button" aria-pressed="true" value="ثبت فرم">
    </a>
</form>
</div>
</div>
</center>
{% endblock %}

templates/forms/done.html
okey

templates/forms/form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

templates/forms/forms.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add Project</button>
</form>

templates/forms/h.html
{% for i in deta %}
    {{f.information}}
{% endfor %}

templates/forms/home.html
<center>فورم شما با موفقیت ثبت شد</center>

templates/forms/save.html
<div>
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo;</a>
    <a href="?page={{ page_obj.previous_page_number }}" type="button">قبلی</a>
{% endif %}
    {% for i in page_obj  %}
    <p>{{i.fname}} {{i.lname}}</p>
    <p>{{i.description}}</p>
    <img src="{{i.pic.url}}" alt="" width="400" height="400">
    {% endfor %}
    <!-- The Modal -->
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">بعدی</a>
    {% endif %} 
  </div>

templates/forms/sms-sender.html
<h1>در حال فرستادن اس ام اس</h1>

templates/forms/submit.html
<center>
    <h1>
        فرم شما با  موفقیت ثبت شد
    </h1>
</center>